#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process without using kill/killall

pid=$(pgrep -f 4-to_infinity_and_beyond)
[ -n "$pid" ] && pkill -STOP -P "$pid" && pkill -CONT -P "$pid" && pkill -TERM -P "$pid"
