#!/usr/bin/env bash
# Infinite loop script that handles SIGTERM by printing a message instead of terminating

term_handler() {
    echo "I am invincible!!!"
}

trap term_handler SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
