#!/usr/bin/env bash
# 7-highlander: Prints a message and handles SIGTERM gracefully

# Function to handle SIGTERM
handle_sigterm() {echo "I am invincible!!!"}

# Set trap
trap handle_sigterm SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
