#!/usr/bin/env bash

# Handle SIGTERM by printing the required message
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop with sleep and echo
while true
do
    echo "To infinity and beyond"
    sleep 2
done
